### PR TITLE
Add GaelVaroquaux as a maintainer

### PR DESCRIPTION
**Pull request by lesteve**

### CODE REVIEW

**Comment by ocefpaf** [comment]
No need to wait for the CIs on this one.

@GaelVaroquaux you should receive a GitHub e-mail inviting you to the @conda-forge/nilearn team. That will give you write access to this feedstock. (Sometimes the e-mail takes 2-3 days and may go to spam! Let me know if you do not get it.)

**Comment by lesteve** [comment]
Great, thanks @ocefpaf!

**Comment by lesteve** [comment]
Oops Circle [failed](https://circleci.com/gh/conda-forge/nilearn-feedstock/24?utm_campaign=build-failed&utm_medium=email&utm_source=notification) on master. Is that because nilearn 0.3.1 was already uploaded and I should have bumped the build number or something?

**Comment by ocefpaf** [comment]
> Oops Circle [failed](https://circleci.com/gh/conda-forge/nilearn-feedstock/24?utm_campaign=build-failed&utm_medium=email&utm_source=notification) on master. Is that because nilearn 0.3.1 was already uploaded and I should have bumped the build number or something?

No need for a new package. The goal here to add a team member. We could've used `skip ci` BTW.

**Comment by GaelVaroquaux** [comment]
Hi @ocefpaf and @lesteve : I really cannot find the conda-forge/nilearn invitation email. Is there something that you can do to resend it?

**Comment by ocefpaf** [comment]
@GaelVaroquaux the bot may take a while to process that but watch your spam folder in any case.
I'll watch it here and if the invite is not dispatched this week I'll check if I can do it manually.

**Comment by GaelVaroquaux** [comment]
OK, I'll wait. No problem!

**Pull request merged**
