### PR TITLE
MNT: Re-rendered with conda-smithy 1.4.6 [ci skip]

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by lesteve** [comment]
Sorry, I am a bit confused did you do `conda smithy rerender` but somehow have a different conda environment than I have ?

Could this be related to the fact that I don't have any token as the output indicates when I run `conda smithy rerender`

```
No circle token.  Create a token at https://circleci.com/account/api and
put it in ~/.conda-smithy/circle.token
No appveyor token. Create a token at https://ci.appveyor.com/api-token and
Put one in ~/.conda-smithy/appveyor.token
No anaconda token. Create a token via
  anaconda auth --create --name conda-smithy --scopes "repos conda api"
and put it in ~/.conda-smithy/anaconda.token
```

I think I'll merge this one once AppVeyor comes back green.

**Comment by jakirkham** [comment]
This is a question we have been asking ourselves about for a long time. ( https://github.com/conda-forge/conda-smithy/issues/223 )

This is a very difficult problem to reproduce, but we definitely have reproduced it on re-rendering bots and the like. The current theory is there is something from `defaults` that is causing this issue, but we don't know what. So switching all possible packages in `root` to use `conda-forge` seems to solve this issue. Also old versions of `conda-build-all` seemed to suffer from this issue more often. So upgrading `conda-build-all` to 1.0.0+ helps. Would try these and see how it goes.

Though there are other outstanding questions like why the problem can [appear/disappear without changing one's environment](https://github.com/conda-forge/conda-smithy/issues/223#issuecomment-257865714). We don't have good answers ATM. 😞

**Comment by jakirkham** [comment]
Also would add that keeping the build requirements minimal seems to help keep this issue at bay. So I'd go back through and cut those down to `python`, `setuptools`, and whatever else is really needed for the build and not just install time.

**Comment by jakirkham** [comment]
> Could this be related to the fact that I don't have any token as the output indicates when I run `conda smithy rerender`

Sorry missed this part. No this has no relation. I don't normally keep tokens around and haven't had any issues because of it.

**Comment by lesteve** [comment]
Hmm OK thanks a lot for the details!

> Also would add that keeping the build requirements minimal seems to help keep this issue at bay. So I'd go back through and cut those down to python, setuptools, and whatever else is really needed for the build and not just install time.

Not sure what you are suggesting here in particular I am not sure about the difference between build and install time. For completeness, scikit-learn is required at install time. This is slightly historical but this is the approach taken by nilearn in order to provide user-friendly error messages when you try to do `pip install nilearn` without having installed the required dependencies.

**Comment by lesteve** [comment]
> So switching all possible packages in root to use conda-forge seems to solve this issue.

I am slightly reluctant to do that I have to say ...

**Comment by jakirkham** [comment]
So you could have multiple Miniconda installs. Personally I have at least 2 so I can test stuff like `conda-smithy` against Python 2 and 3. Admittedly not the greatest solution, but that's all I can offer for now.

**Comment by jakirkham** [comment]
> Not sure what you are suggesting here in particular the difference between build and install time. 

Normally build time for a pure Python library means copying `.py` files over and compiling them. So this requires the `python` interpreter and `setuptools` if it is used in `setup.py`. Plus anything else `setup.py` imports or is listed in `setup_requires`.

Install time dependencies are what one gets when running `conda install nilearn` for instance.

**Comment by lesteve** [comment]
> So you could have multiple Miniconda installs. Personally I have at least 2 so I can test stuff like conda-smithy against Python 2 and 3. Admittedly not the greatest solution, but that's all I can offer for now.

That sounds fine. Even doing that and making sure I have all the packages installed from conda-forge in this separate miniconda, I still can not rerender similarly to this PR though and always get the same result as #8 when I do `conda smithy rerender`.

I am a bit confused about the AppVeyor error as well, it seems exactly the same as the one in #6. cc @ocefpaf.

**Comment by ocefpaf** [comment]
> I am a bit confused about the AppVeyor error as well, it seems exactly the same as the one in #6. cc @ocefpaf.

They are not the same. This one is from #6 and it fails across the board:

``` shell
Build started
git clone -q https://github.com/conda-forge/nilearn-feedstock.git C:\projects\nilearn-feedstock
git fetch -q origin +refs/pull/6/merge:
git checkout -qf FETCH_HEAD
Running Install scripts
if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod ` https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | ` Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { ` throw "There are newer queued builds for this pull request, failing early." }
rmdir C:\cygwin /s /q
appveyor DownloadFile "https://raw.githubusercontent.com/pelson/Obvious-CI/master/bootstrap-obvious-ci-and-miniconda.py"
Downloading bootstrap-obvious-ci-and-miniconda.py (4,124 bytes)...100%
python bootstrap-obvious-ci-and-miniconda.py %CONDA_INSTALL_LOCN% %TARGET_ARCH% %CONDA_PY:~0,1% --without-obvci
Start-Process : This command cannot be run due to the error: The file or 
directory is corrupted and unreadable.
At line:1 char:1
+ Start-Process -FilePath Miniconda-latest-Windows-x86.exe -ArgumentLis ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOp 
   erationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.C 
   ommands.StartProcessCommand

Downloading from http://repo.continuum.io/miniconda/Miniconda-latest-Windows-x86.exe
Traceback (most recent call last):
  File "bootstrap-obvious-ci-and-miniconda.py", line 103, in <module>
    install_obvci=not args.without_obvci)
  File "bootstrap-obvious-ci-and-miniconda.py", line 78, in main
    subprocess.check_call(cmd)
  File "C:\Python27\lib\subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['powershell', 'Start-Process', '-FilePath', 'Miniconda-latest-Windows-x86.exe', '-ArgumentList', '/S,/D=C:\\conda', '-Wait']' returned non-zero exit status 1
Command exited with code 1
```

This one is from this PR and only fails in Python 3.5:

``` shell

Include the output of the command 'conda info' in your report.
Traceback (most recent call last):
  File "C:\conda\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\conda\lib\site-packages\conda_build\main_build.py", line 151, in main
    args_func(args, p)
  File "C:\conda\lib\site-packages\conda_build\main_build.py", line 412, in args_func
    args.func(args, p)
  File "C:\conda\lib\site-packages\conda_build\main_build.py", line 355, in execute
    debug=args.debug)
  File "C:\conda\lib\site-packages\conda_build\build.py", line 650, in build
    preserve_egg_dir=bool(m.get_value('build/preserve_egg_dir')))
  File "C:\conda\lib\site-packages\conda_build\post.py", line 194, in post_process
    compile_missing_pyc(files)
  File "C:\conda\lib\site-packages\conda_build\post.py", line 190, in compile_missing_pyc
    coerce_pycache_to_old_style(compile_files, cwd=cwd)
  File "C:\conda\lib\site-packages\conda_build\post.py", line 166, in coerce_pycache_to_old_style
    os.rename(fname, f + 'c')
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\conda\\envs\\_build\\Lib\\site-packages\\nilearn\\datasets\\tests\\data\\__pycache__\\__init__.cpython-35.pyc' -> 'C:\\conda\\envs\\_build\\Lib\\site-packages\\nilearn\\datasets\\tests\\data\\__init__.pyc'
Command exited with code 1
```

**Comment by lesteve** [comment]
Not sure what happened to the last AppVeyor build on #6 but this does not match my comment [here](https://github.com/conda-forge/nilearn-feedstock/pull/6#issuecomment-251103966). At the time the build matrix on AppVeyor looked like this:
https://ci.appveyor.com/project/conda-forge/nilearn-feedstock/build/1.0.13

I do believe this is exactly the same error.

**Comment by ocefpaf** [comment]
> I do believe this is exactly the same error.

Indeed. You were hit bug the bug in the process of making #6. The rerendering fixed that bug, but the original error persists. @msarahan any idea of what is going on there?

**Comment by jakirkham** [comment]
Closing in favor of PR ( https://github.com/conda-forge/nilearn-feedstock/pull/11 ).

**Pull request closed without merging**
