### PR TITLE
Update to 0.4.0

### PR DESCRIPTION
**Pull request by KamalakerDadi**
Wanted to update to new release 0.4.0.

I am new to this one. Basically, followed the other update PR as suggested by @lesteve .

### CODE REVIEW

**Comment by lesteve** [comment]
LGTM although I am not an expert, @ocefpaf WDYT?

**Comment by lesteve** [comment]
@KamalakerDadi I added you as maintainer. I think you are supposed to get an automated email that give you the rights. See https://github.com/conda-forge/nilearn-feedstock/pull/16#issuecomment-329203691 for more details:

> @GaelVaroquaux you should receive a GitHub e-mail inviting you to the @conda-forge/nilearn team. That will give you write access to this feedstock. (Sometimes the e-mail takes 2-3 days and may go to spam! Let me know if you do not get it.)

**Comment by lesteve** [comment]
This seems fine: `conda search -c conda-forge nilearn` does list nilearn 0.4.0.

**Comment by KamalakerDadi** [comment]
Thanks a lot @lesteve

**Pull request merged**
