### PR TITLE
MNT: Updated the feedstock for conda-smithy version 1.3.1.

### PR DESCRIPTION
**Pull request by lesteve**
Takes over #4 on the latest master which has the additional setuptools dependency to make sure that all the CIs are green.

### CODE REVIEW

**Comment by lesteve** [comment]
Hmmm AppVeyor fails for Python 3.5 with this error:

```
Traceback (most recent call last):
  File "C:\conda\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\conda\lib\site-packages\conda_build\main_build.py", line 151, in main
    args_func(args, p)
  File "C:\conda\lib\site-packages\conda_build\main_build.py", line 412, in args_func
    args.func(args, p)
  File "C:\conda\lib\site-packages\conda_build\main_build.py", line 355, in execute
    debug=args.debug)
  File "C:\conda\lib\site-packages\conda_build\build.py", line 650, in build
    preserve_egg_dir=bool(m.get_value('build/preserve_egg_dir')))
  File "C:\conda\lib\site-packages\conda_build\post.py", line 194, in post_process
    compile_missing_pyc(files)
  File "C:\conda\lib\site-packages\conda_build\post.py", line 190, in compile_missing_pyc
    coerce_pycache_to_old_style(compile_files, cwd=cwd)
  File "C:\conda\lib\site-packages\conda_build\post.py", line 166, in coerce_pycache_to_old_style
    os.rename(fname, f + 'c')
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\conda\\envs\\_build\\Lib\\site-packages\\nilearn\\datasets\\tests\\data\\__pycache__\\__init__.cpython-35.pyc' -> 'C:\\conda\\envs\\_build\\Lib\\site-packages\\nilearn\\datasets\\tests\\data\\__init__.pyc'
Command exited with code 1
```

Full log [here](https://ci.appveyor.com/project/conda-forge/nilearn-feedstock/build/job/5msdni96akarxkwj).

@conda-forge/core any hint on this one? A quick google search didn't give anything ...

**Comment by msarahan** [comment]
Should be fixed in conda-build 2.0.2, or 1.21.11

**Comment by lesteve** [comment]
I see thanks! I am very new to this conda-forge business I am afraid. Should I wait for an automated PR like #4 that gently nudges me into updating the recipe generated with a newest version of conda-smithy? Should I merge this PR in the mean-time?

**Comment by lesteve** [comment]
Rereading this I have probably mixed up conda-smithy and conda-build in my previous comment. So I am guessing this will be fixed whenever the build infrastructure uses a conda-build version with the fix.

**Comment by ocefpaf** [comment]
@lesteve can you update `conda-smithy` and re-render again? We just fixed a bug that should help here.

**Comment by lesteve** [comment]
@ocefpaf I opened #8, let's see how that goes.

**Comment by lesteve** [comment]
BTW, out of curiosity, any reason why conda 4.2 is not available through conda-forge? I had to downgrade conda in my root environment in order to be able to install conda-smithy.

**Pull request closed without merging**
